[meta]
name     = "Map Together"
author   = "XertroV"
category = "Map Editor"
version  = "0.2.6"
siteid   = 521

[script]
#__DEFINES__
dependencies = ["VehicleState", "Camera", "Editor"]
exports = ["Export_Imports.as"]
shared_exports = ["Export_Shared.as"]

timeout = 30000
module = "MapTogether"
