[meta]
name     = "Map Together"
author   = "XertroV"
category = "Map Editor"
version  = "0.1.0"
siteid   = 521

[script]
#__DEFINES__
optional_dependencies = ["Editor", "editor"]
dependencies = ["VehicleState", "Camera"]

timeout = 75000
