[meta]
name     = "Map Together"
author   = "XertroV"
category = "Map Editor"
version  = "0.1.7"
siteid   = 521

[script]
#__DEFINES__
optional_dependencies = ["Editor", "editor"]
dependencies = ["VehicleState", "Camera"]
exports = ["Export_Imports.as"]
shared_exports = ["Export_Shared.as"]

timeout = 20000
module = "MapTogether"
